### ISSUE TITLE
can' t edit transport options and the version of nodemailer is outdated

### ISSUE THREAD

**Issue by ivanhuay** [zhaosiyang/nodemailer-promise#1]
there is no way to edit transporter configuration of node mailer.

in the nodemailer documentation you can find the options:
https://nodemailer.com/smtp/

### General options
* service – can be set to the name of a well-known service so you don’t have to input the port, host, and secure options (see Well-known Services)
* port – is the port to connect to (defaults to 587 is secure is false or 465 if true)
* host – is the hostname or IP address to connect to (defaults to ‘localhost’)
* auth – defines authentication data (see authentication section below)
authMethod – defines preferred authentication method, defaults to ‘PLAIN’
### TLS options
* secure – if true the connection will use TLS when connecting to server. If false (the default) then TLS is used if server supports the STARTTLS extension. In most cases set this value to true if you are connecting to port 465. For port 587 or 25 keep it false
* tls – defines additional node.js TLSSocket options to be passed to the socket constructor, eg. {rejectUnauthorized: true}.
* ignoreTLS – if this is true and secure is false then TLS is not used even if the server supports STARTTLS extension
* requireTLS – if this is true and secure is false then Nodemailer tries to use STARTTLS even if the server does not advertise support for it. If the connection can not be encrypted then message is not sent

## the latest version of nodemailer is 4.0.1

**Comment by zhaosiyang** [comment]
fixed
